### PR TITLE
Revamp entire build process

### PR DESCRIPTION
**Pull request by Pierstoval**
Ideal goal:

In one single package, I'd like these things:

1. Use the package normally in a Svelte project with standard imports:
    ```js
    // src/App.svelte
    import { DashboardDefinition } from '@orbitale/svelte-admin';
    import { carbon } from '@orbitale/svelte-admin/themes'; // NOTE: this path must be a sub-path in the project, not a separate package
    // ... their code
    ```
2. In a plain HTML file, I want people to be able to load the exact same package but without any bundler:
    ```html
    <html>
    <head><!-- ... --></head>
    <body>
        <script type="module">
            import { DashboardDefinition } from 'https://whatever.cdn.com/@orbitale/svelte-admin/index.js';
            import { carbon } from 'https://whatever.cdn.com/@orbitale/svelte-admin/themes/index.js';
            // ... their code
        </script>
    </body>
    </html>
    ```
3. Do the same as 2, but instead of Svelte components in the `themes` path, it's WebComponents only (if step 2 works perfectly with no bundler, and WebComponents are complicated to implement, maybe it's optional)

### CODE REVIEW

**Comment by Pierstoval** [comment]
Example of a generated tarball:

[orbitale-svelte-admin-0.16.3.tgz](https://github.com/user-attachments/files/16090799/orbitale-svelte-admin-0.16.3.tgz)

**Comment by GlistenSTAR** [comment]
Hello, @Pierstoval 
Do you have done yourself?

**Comment by Pierstoval** [comment]
@GlistenSTAR It's still not finished, I'm trying to work on it, but not sure whether it's gonna be a success or not.

**Comment by Pierstoval** [comment]
Turns out I could do it with `svelte-package` and some adjustments in the package.json file and files architecture in the end. Merged this, but it wasn't really useful for what it was.

Package is now properly compiled for now. Maybe other improvements might come, but so far it's okay.

**Pull request merged**
